name: PR
on: [ pull_request ]
jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ./*
          key: ${{ github.sha }}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ init ]
    steps:
      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Init NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Packages
        run: npm install
        shell: bash
      - name: Build
        run: npm run build
